//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace U_Commerce.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class ProductClosed
    {
        [Required]
        [Display(Name = "Product")]
        public int ProductId { get; set; }

        public Nullable<System.DateTime> DateTime { get; set; }

        [Required]
        [Display(Name = "Close Type")]
        public int ClosingTypeId { get; set; }
    
        public virtual Product Product { get; set; }
        public virtual ProductCloseType ProductCloseType { get; set; }
    }
}
