//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace U_Commerce.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class UserVerified
    {
        [Required]
        [Display(Name ="User")]
        public int UserId { get; set; }
        public System.DateTime DateTime { get; set; }
        public string Ip { get; set; }
    
        public virtual User User { get; set; }
    }
}
